services:
  postgres:
    image: postgres:16-alpine
    container_name: praevon_postgres
    restart: unless-stopped
    env_file:   
      - .env
    ports:
      - "${POSTGRES_LOCAL_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - praevon_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
    driver: local

networks:
  praevon_network:
    driver: bridge
